### ISSUE TITLE
[Tracking issue] Deprecations and inaccurate docs

### ISSUE THREAD

**Issue by meowsbits** [ethereum/hive#191]
There are several packages and/or tools housed in this repository that are, [according to](https://github.com/ethereum/hive/issues/184#issuecomment-470898941) @holiman, unmaintained and now nonfunctional, which is rather a different picture than is presented on the README:

> Note: All smoke tests must pass for a client to be included into hive.
> https://github.com/ethereum/hive#smoke-testing-new-clients

... versus what I'm learning through some comments here and there:

> I'm afraid I've never tested with the smoke tests... I only run the simulator consensus2
> https://github.com/ethereum/hive/issues/189#issuecomment-470897546

This is a tracking issue to organize discussion for what to do with the broken tests and documentation, and to serve as a PSA for newcomers attempting to use Hive.

As far as I can see, these tests and/or clients should be either removed (both from code and docs), or fixed. At this point it seems the former
may be more reasonable, but curious for feedback from the maintainers.

- [ ] https://github.com/ethereum/hive/issues/1: Promote hive to be the standard Ethereum compatibility checker 
- [ ] https://github.com/ethereum/hive/issues/21: Error during running `hive --client=go-ethereum:develop --test=NONE --sim=.`
- [x] https://github.com/ethereum/hive/issues/127: Failed to simulate clients saying the system has go1.11 while go-ethereum requires >go1.4
- [x] https://github.com/ethereum/hive/issues/171: Hive broken if not using `docker-noshell`
- [x] https://github.com/ethereum/hive/issues/177: --sim=devp2p.* --client=go-eth.* : panic: runtime error: invalid memory address or nil pointer dereference
- [ ] https://github.com/ethereum/hive/issues/184: --client='go.*master' --sim='.*issues.*' : failed to lookup bridge IP
- [ ] https://github.com/ethereum/hive/issues/185: --client='go.*master' --sim='.*ethereum.*' : go-ethereum requires at least Go version 1.4 and cannot be compiled with an earlier version
- [x] https://github.com/ethereum/hive/issues/186: --client='go.*stable' --smoke: program stalls
- [x] https://github.com/ethereum/hive/issues/188: --client='parity.*beta' --smoke: cargo not found (The location of rustup.sh has moved.)
- [x] https://github.com/ethereum/hive/issues/189: --client='parity.*stable' : Failed to identify the stable branch.
- [x] https://github.com/ethereum/hive/issues/190: Hive installation fails
