### ISSUE TITLE
Remaining Engine API Cancun Tests

### ISSUE THREAD

**Issue by marioevz** [ethereum/hive#810]
Extracted list of remaining tasks for Cancun Engine API from https://github.com/ethereum/hive/pull/759
```[tasklist]
### Tasks
- [ ] Implement tests for https://github.com/ethereum/execution-apis/pull/426
- [ ] Field checking of new engine api methods, pre and post fork
- [ ] Sync Tests
- [ ] Parallelism Tests
- [ ] Auto-generate README.md from the information in the test case list
```

**Comment by jochem-brouwer** [comment]
This seems currently untested:

- [ ] `forkchoiceUpdatedV2` throws `INVALID_PARAMS` if `parentBlockBeaconRoot` is provided
- [ ] `forkchoiceUpdatedV3` throws `UNSUPPORTED_FORK` if it is called at `< Cancun` time
- [ ] `getPayloadV3` throws `UNSUPPORTED_FORK` is a pre-Cancun payload is requested
